weights: weights/yolov5x.pt
cfg: models/yolov5xc.yaml
data: data/voc-fish.yaml
hyp: data/hyp.finetune.yaml
epochs: 50
batch_size: 4
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
name: ''
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
workers: 8
total_batch_size: 4
world_size: 1
global_rank: -1
